### ISSUE TITLE
Inline styling on elements

### ISSUE THREAD

**Issue by Brandoncapecci** [blom/haml-coderay#1]
The standard CodeRay library adds classes to the spans so they can be styled like .CodeRay .symbol { color: #FFF; } How do I get these classes back and remove the inline styling? 
![Screen Shot 2013-03-13 at 4 31 06 AM](https://f.cloud.github.com/assets/1141779/253423/eec607c0-8bd1-11e2-943b-703b9429b5e1.png)

**Comment by blom** [comment]
Hi! Try this:

``` ruby
Haml::Filters::CodeRay.encoder_options = { :css => :class }
```

**Comment by Brandoncapecci** [comment]
Awesome, thanks!
